# ndarray 연산
- NumPy 배열 간 연산 정리임
- 원소별 연산, broadcasting, 행렬곱, axis 연산 포함함


In [1]:
import numpy as np

## n차원 배열 연산
- 같은 shape끼리 원소별 연산 가능함
- 같은 위치의 값끼리 계산함
- 결과 shape도 기존 shape와 같음


In [10]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.full_like(arr1, 2)

# print(arr1 + arr2)
# print(arr1 - arr2)
# print(arr1 * arr2)
# print(arr1 / arr2)
# print(arr1 // arr2)
# print(arr1 % arr2)
# print(arr1 ** arr2)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


## broadcasting 연산 방식
- shape가 다른 배열도 규칙이 맞으면 연산 가능함
- 작은 배열을 큰 배열 shape에 맞춰 해석함
- 실제 배열을 복사해서 키우는 것은 아님

**broadcasting 규칙**
- 뒤쪽 차원부터 비교함
- 두 차원이 같으면 가능함
- 둘 중 하나가 1이면 가능함
- 둘 다 다르고 1도 아니면 불가함

![](https://d.pr/i/D0XITM+)
![](https://d.pr/i/fka9ED+)


## 행렬곱셈 Matrix Multiplication
- 점곱연산 Dot Product, 내적이라고도 함
- NumPy의 `*` 연산과 행렬곱은 다름
- `*`: 같은 위치 원소끼리 곱함
- `@`, `np.dot()`, `np.matmul()`: 행렬곱 수행함

**계산 방식**
- 왼쪽 행과 오른쪽 열을 짝지어 계산함
- 같은 위치끼리 곱한 뒤 모두 더함
- 결과의 한 칸은 왼쪽 행과 오른쪽 열의 내적값임

**shape 조건**
- 첫 번째 행렬의 열 수와 두 번째 행렬의 행 수가 같아야 함
- `(m, n) @ (n, p) -> (m, p)` 형태임
- 결과 shape는 바깥쪽 숫자인 `(m, p)`임

**수식 표현**
- 결과[i, j] = A의 i번째 행과 B의 j번째 열을 곱해서 더한 값임
- 계산 흐름: `A행 원소 * B열 원소`를 모두 더함

**예시**
- A = `[[1, 2], [3, 4]]`임
- B = `[[5, 6], [7, 8]]`임
- 결과[0, 0] = `1*5 + 2*7 = 19`임
- 결과[0, 1] = `1*6 + 2*8 = 22`임
- 결과[1, 0] = `3*5 + 4*7 = 43`임
- 결과[1, 1] = `3*6 + 4*8 = 50`임
- 최종 결과 = `[[19, 22], [43, 50]]`임


## 기타 연산
- 절대값, 반올림, 올림, 내림, 버림 등 기본 수학 함수 정리임


### axis 속성
- 연산을 처리할 축 지정값임
- `axis=None`: 전체 값을 하나로 펼쳐 계산함
- `axis=0`: 행 방향으로 내려가며 계산함, 열별 결과가 남음
- `axis=1`: 열 방향으로 이동하며 계산함, 행별 결과가 남음
- 핵심: axis는 계산 후 사라지는 축임
